"""adding followers

Revision ID: 00781a6e36d8
Revises: 83b34d37514c
Create Date: 2018-09-14 22:27:22.810748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00781a6e36d8'
down_revision = '83b34d37514c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
