"""adding admin support

Revision ID: 24cb272fe5ab
Revises: 1b6a45851ea6
Create Date: 2018-11-12 20:34:38.694144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24cb272fe5ab'
down_revision = '1b6a45851ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_super', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_super')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
