"""add invite_me flag

Revision ID: 9a905eed7848
Revises: f71bc76024e7
Create Date: 2018-12-18 21:33:51.995160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a905eed7848'
down_revision = 'f71bc76024e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invite_me', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'invite_me')
    # ### end Alembic commands ###
