"""adding canteen support

Revision ID: dd0859a3839e
Revises: 9a905eed7848
Create Date: 2019-04-24 08:26:30.488892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0859a3839e'
down_revision = '9a905eed7848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('canteen', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_user_canteen'), 'user', ['canteen'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_canteen'), table_name='user')
    op.drop_column('user', 'canteen')
    # ### end Alembic commands ###
