"""adding timezone support

Revision ID: f71bc76024e7
Revises: b0a820e16bd0
Create Date: 2018-12-18 20:40:13.020150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71bc76024e7'
down_revision = 'b0a820e16bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timezone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timezone_name'), 'timezone', ['name'], unique=True)
    op.add_column('user', sa.Column('tz_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'timezone', ['tz_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'tz_id')
    op.drop_index(op.f('ix_timezone_name'), table_name='timezone')
    op.drop_table('timezone')
    # ### end Alembic commands ###
